#pragma once

#define LUG_VULKAN_PHYSICAL_DEVICE_FEATURES(macro)  \
    macro(robustBufferAccess)                       \
    macro(fullDrawIndexUint32)                      \
    macro(imageCubeArray)                           \
    macro(independentBlend)                         \
    macro(geometryShader)                           \
    macro(tessellationShader)                       \
    macro(sampleRateShading)                        \
    macro(dualSrcBlend)                             \
    macro(logicOp)                                  \
    macro(multiDrawIndirect)                        \
    macro(drawIndirectFirstInstance)                \
    macro(depthClamp)                               \
    macro(depthBiasClamp)                           \
    macro(fillModeNonSolid)                         \
    macro(depthBounds)                              \
    macro(wideLines)                                \
    macro(largePoints)                              \
    macro(alphaToOne)                               \
    macro(multiViewport)                            \
    macro(samplerAnisotropy)                        \
    macro(textureCompressionETC2)                   \
    macro(textureCompressionASTC_LDR)               \
    macro(textureCompressionBC)                     \
    macro(occlusionQueryPrecise)                    \
    macro(pipelineStatisticsQuery)                  \
    macro(vertexPipelineStoresAndAtomics)           \
    macro(fragmentStoresAndAtomics)                 \
    macro(shaderTessellationAndGeometryPointSize)   \
    macro(shaderImageGatherExtended)                \
    macro(shaderStorageImageExtendedFormats)        \
    macro(shaderStorageImageMultisample)            \
    macro(shaderStorageImageReadWithoutFormat)      \
    macro(shaderStorageImageWriteWithoutFormat)     \
    macro(shaderUniformBufferArrayDynamicIndexing)  \
    macro(shaderSampledImageArrayDynamicIndexing)   \
    macro(shaderStorageBufferArrayDynamicIndexing)  \
    macro(shaderStorageImageArrayDynamicIndexing)   \
    macro(shaderClipDistance)                       \
    macro(shaderCullDistance)                       \
    macro(shaderFloat64)                            \
    macro(shaderInt64)                              \
    macro(shaderInt16)                              \
    macro(shaderResourceResidency)                  \
    macro(shaderResourceMinLod)                     \
    macro(sparseBinding)                            \
    macro(sparseResidencyBuffer)                    \
    macro(sparseResidencyImage2D)                   \
    macro(sparseResidencyImage3D)                   \
    macro(sparseResidency2Samples)                  \
    macro(sparseResidency4Samples)                  \
    macro(sparseResidency8Samples)                  \
    macro(sparseResidency16Samples)                 \
    macro(sparseResidencyAliased)                   \
    macro(variableMultisampleRate)                  \
    macro(inheritedQueries)
