# Find glTF2-loader
#
# Below are the output variables:
#  - GLTF2-LOADER_INCLUDE_DIR
#  - GLTF2-LOADER_LIBRARY
#  - GLTF2-LOADER_FOUND


find_path(GLTF2-LOADER_INCLUDE_DIR
    NAMES gltf2/glTF2.hpp
    PATHS $ENV{GLTF2-LOADER_ROOT} ${GLTF2-LOADER_ROOT}
    PATH_SUFFIXES include
    CMAKE_FIND_ROOT_PATH_BOTH
)

find_library(GLTF2-LOADER_LIBRARY
    NAMES gltf2-loader
    PATHS $ENV{GLTF2-LOADER_ROOT} ${GLTF2-LOADER_ROOT}
    PATH_SUFFIXES lib64 lib/${ANDROID_ABI}
    CMAKE_FIND_ROOT_PATH_BOTH
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLTF2-Loader FOUND_VAR GLTF2-LOADER_FOUND REQUIRED_VARS GLTF2-LOADER_LIBRARY GLTF2-LOADER_INCLUDE_DIR)

mark_as_advanced(GLTF2-LOADER_INCLUDE_DIR GLTF2-LOADER_LIBRARY)
